package definition

import (
	"reflect"
	"strings"
	"testing"
	"time"

	"github.com/daboss2003/mooring/internal/compose"
)

// legacyHealthDef is an existing-style definition: bare exec-array healthchecks, the only form
// before the mapping form existed.
const legacyHealthDef = `apiVersion: mooring/v1
kind: App
metadata:
  slug: shop
spec:
  compose:
    source: generated
    services:
      api:
        image: ghcr.io/acme/api:1
        ports:
          - internal: 3000
        env:
          NODE_ENV: production
          DB_PASSWORD: { secret: DB_PASSWORD }
        depends_on: [emqx]
        healthcheck: [wget, -qO-, http://localhost:3000/health/live]
        restart: unless-stopped
        stop_grace_period: 60s
      emqx:
        image: emqx/emqx:5.8.3
        command: [emqx, foreground]
        healthcheck: ["/opt/emqx/bin/emqx", ctl, status]
        ports:
          - internal: 8883
            publish: true
            public: true
        volumes:
          - name: emqx_data
            target: /opt/emqx/data
  secrets:
    - name: DB_PASSWORD
  edge:
    routes:
      - hostname: api.example.com
        service: api
        port: 3000
`

// legacyHealthCanonical is Canonical(Parse(legacyHealthDef)) as rendered by the code BEFORE the
// mapping form existed (captured from that build). Stored canonicals are re-parsed on every
// read, so this must stay byte-identical.
const legacyHealthCanonical = `apiVersion: mooring/v1
kind: App
metadata:
  slug: shop
spec:
  compose:
    source: generated
    services:
      api:
        image: ghcr.io/acme/api:1
        ports:
          - internal: 3000
            publish: false
            public: false
        env:
          DB_PASSWORD:
            secret: DB_PASSWORD
          NODE_ENV: production
        healthcheck:
          - wget
          - -qO-
          - http://localhost:3000/health/live
        restart: unless-stopped
        depends_on:
          - emqx
        stop_grace_period: 60s
      emqx:
        image: emqx/emqx:5.8.3
        ports:
          - internal: 8883
            publish: true
            public: true
        volumes:
          - name: emqx_data
            source: ""
            target: /opt/emqx/data
            read_only: false
        command:
          - emqx
          - foreground
        healthcheck:
          - /opt/emqx/bin/emqx
          - ctl
          - status
  secrets:
    - name: DB_PASSWORD
      generate: ""
  edge:
    routes:
      - hostname: api.example.com
        service: api
        port: 3000
        path_prefix: ""
        hsts: false
        security_headers: false
        redirect_http: false
`

// legacyHealthCompose is ComposeBytes(Parse(legacyHealthDef)) as generated by the code BEFORE
// the healthcheck timing fields existed (captured from that build). Byte-identical output means
// docker compose sees an unchanged service config, so an upgrade recreates nothing.
const legacyHealthCompose = `name: shop
services:
    api:
        image: ghcr.io/acme/api:1
        restart: unless-stopped
        environment:
            - DB_PASSWORD=${DB_PASSWORD}
            - NODE_ENV=production
        healthcheck:
            test:
                - CMD
                - wget
                - -qO-
                - http://localhost:3000/health/live
        depends_on:
            - emqx
        stop_grace_period: 60s
    emqx:
        image: emqx/emqx:5.8.3
        ports:
            - 8883:8883
        volumes:
            - emqx_data:/opt/emqx/data
        command:
            - emqx
            - foreground
        healthcheck:
            test:
                - CMD
                - /opt/emqx/bin/emqx
                - ctl
                - status
volumes:
    emqx_data: null
`

func TestHealthcheckArrayFormByteIdentical(t *testing.T) {
	d, err := Parse([]byte(legacyHealthDef))
	if err != nil {
		t.Fatalf("existing-style definition rejected: %v", err)
	}
	canon, err := Canonical(d)
	if err != nil {
		t.Fatal(err)
	}
	if string(canon) != legacyHealthCanonical {
		t.Fatalf("canonical changed for an array healthcheck:\n--- got\n%s\n--- want\n%s", canon, legacyHealthCanonical)
	}
	// A stored canonical re-parses and re-marshals to itself (the read path is a fixed point).
	stored, err := Parse([]byte(legacyHealthCanonical))
	if err != nil {
		t.Fatalf("stored canonical no longer parses: %v", err)
	}
	if again, _ := Canonical(stored); string(again) != legacyHealthCanonical {
		t.Fatalf("stored canonical did not re-marshal byte-identically:\n%s", again)
	}
	raw, err := ComposeBytes(stored)
	if err != nil {
		t.Fatal(err)
	}
	if string(raw) != legacyHealthCompose {
		t.Fatalf("generated compose changed for an array healthcheck:\n--- got\n%s\n--- want\n%s", raw, legacyHealthCompose)
	}
}

func healthDoc(healthcheck string) []byte {
	return []byte(docWith("  compose:\n    services:\n      web:\n        image: nginx:1\n        healthcheck: " + healthcheck + "\n"))
}

func TestHealthcheckMappingForm(t *testing.T) {
	src := docWith(`  compose:
    services:
      web:
        image: nginx:1
        healthcheck:
          test: [wget, -qO-, http://localhost:3000/health]
          interval: 10s
          timeout: 5s
          retries: 4
          start_period: 60s
`)
	d, err := Parse([]byte(src))
	if err != nil {
		t.Fatalf("mapping healthcheck rejected: %v", err)
	}
	hc := d.Spec.Compose.Services["web"].Healthcheck
	if hc == nil || strings.Join(hc.Test, " ") != "wget -qO- http://localhost:3000/health" {
		t.Fatalf("test not parsed: %+v", hc)
	}
	if hc.IntervalD() != 10*time.Second || hc.TimeoutD() != 5*time.Second || hc.RetriesN() != 4 || hc.StartPeriodD() != time.Minute {
		t.Errorf("accessors = %v %v %d %v", hc.IntervalD(), hc.TimeoutD(), hc.RetriesN(), hc.StartPeriodD())
	}

	// The canonical keeps the mapping and re-parses to the same values.
	canon, err := Canonical(d)
	if err != nil {
		t.Fatal(err)
	}
	wantCanon := "        healthcheck:\n          test:\n            - wget\n            - -qO-\n            - http://localhost:3000/health\n" +
		"          interval: 10s\n          timeout: 5s\n          retries: 4\n          start_period: 60s\n"
	if !strings.Contains(string(canon), wantCanon) {
		t.Errorf("canonical missing the mapping healthcheck:\n%s", canon)
	}
	d2, err := Parse(canon)
	if err != nil {
		t.Fatalf("canonical did not re-parse: %v\n%s", err, canon)
	}
	if got := d2.Spec.Compose.Services["web"].Healthcheck; got == nil || !reflect.DeepEqual(*got, *hc) {
		t.Errorf("healthcheck did not round-trip: %+v", got)
	}

	// The generated compose carries every timing key and passes §5.6 + the full reconcile gate.
	raw, err := ComposeBytes(d)
	if err != nil {
		t.Fatal(err)
	}
	wantCompose := "        healthcheck:\n            test:\n                - CMD\n                - wget\n                - -qO-\n                - http://localhost:3000/health\n" +
		"            interval: 10s\n            timeout: 5s\n            retries: 4\n            start_period: 60s\n"
	if !strings.Contains(string(raw), wantCompose) {
		t.Errorf("generated compose missing the timing keys:\n%s", raw)
	}
	if strings.Contains(string(raw), "start_interval") {
		t.Errorf("start_interval must never be generated:\n%s", raw)
	}
	if res := compose.ValidateBytes(raw, compose.Env{}, "/run/app", compose.Options{}); !res.OK() {
		t.Fatalf("generated compose failed §5.6: %s", res.Error())
	}
	if err := Validate(d, "/run/app", compose.Env{}, nil); err != nil {
		t.Errorf("mapping healthcheck must pass the reconcile gate: %v", err)
	}
}

// A mapping with only `test` is the same healthcheck as the bare array, so it canonicalizes to
// the array form.
func TestHealthcheckMappingTestOnlyCanonicalizesToArray(t *testing.T) {
	fromMap, err := Parse(healthDoc("{test: [wget, -qO-, http://localhost/health]}"))
	if err != nil {
		t.Fatal(err)
	}
	fromArr, err := Parse(healthDoc("[wget, -qO-, http://localhost/health]"))
	if err != nil {
		t.Fatal(err)
	}
	a, _ := Canonical(fromMap)
	b, _ := Canonical(fromArr)
	if string(a) != string(b) {
		t.Errorf("test-only mapping should canonicalize to the array form:\n--- mapping\n%s\n--- array\n%s", a, b)
	}
	if !strings.Contains(string(a), "healthcheck:\n          - wget\n") {
		t.Errorf("expected the bare array form:\n%s", a)
	}
}

func TestHealthcheckAccepts(t *testing.T) {
	for name, hc := range map[string]string{
		"array":                    "[curl, -f, http://localhost/health]",
		"array keeps CMD (compat)": "[CMD, curl, -f, http://localhost/health]",
		"test only":                "{test: [curl, -f, http://localhost/health]}",
		"interval floor":           "{test: [curl], interval: 1s}",
		"interval ceiling":         "{test: [curl], interval: 10m}",
		"timeout floor":            "{test: [curl], timeout: 1s}",
		"timeout ceiling":          "{test: [curl], timeout: 5m}",
		"retries floor":            "{test: [curl], retries: 1}",
		"retries ceiling":          "{test: [curl], retries: 20}",
		"start_period zero":        "{test: [curl], start_period: 0s}",
		"start_period bare zero":   "{test: [curl], start_period: 0}",
		"start_period ceiling":     "{test: [curl], start_period: 30m}",
		"compound duration":        "{test: [curl], interval: 1m30s}",
		"null field is unset":      "{test: [curl], interval: ~, retries: ~}",
	} {
		if _, err := Parse(healthDoc(hc)); err != nil {
			t.Errorf("%s: %s rejected: %v", name, hc, err)
		}
	}
}

func TestHealthcheckRejects(t *testing.T) {
	for name, hc := range map[string]string{
		"shell string":           `"curl -f http://localhost/health || exit 1"`,
		"mapping shell test":     `{test: "curl -f http://localhost/health"}`,
		"leading CMD":            "{test: [CMD, curl, -f, http://localhost/health]}",
		"leading CMD-SHELL":      `{test: [CMD-SHELL, "curl -f http://localhost/health"]}`,
		"leading NONE":           "{test: [NONE]}",
		"missing test":           "{interval: 10s}",
		"empty test":             "{test: [], interval: 10s}",
		"null test":              "{test: ~}",
		"empty mapping":          "{}",
		"empty argument":         `{test: [curl, ""]}`,
		"newline argument":       `{test: ["curl\n-f"]}`,
		"start_interval":         "{test: [curl], start_interval: 5s}",
		"disable":                "{test: [curl], disable: true}",
		"interval not scalar":    "{test: [curl], interval: [10s]}",
		"interval no unit":       "{test: [curl], interval: 10}",
		"interval garbage":       "{test: [curl], interval: soon}",
		"interval zero":          "{test: [curl], interval: 0s}",
		"interval below floor":   "{test: [curl], interval: 500ms}",
		"interval above ceiling": "{test: [curl], interval: 11m}",
		"timeout zero":           "{test: [curl], timeout: 0s}",
		"timeout above ceiling":  "{test: [curl], timeout: 6m}",
		"start_period negative":  "{test: [curl], start_period: -1s}",
		"start_period above":     "{test: [curl], start_period: 31m}",
		"retries zero":           "{test: [curl], retries: 0}",
		"retries negative":       "{test: [curl], retries: -1}",
		"retries above ceiling":  "{test: [curl], retries: 21}",
		"retries quoted":         `{test: [curl], retries: "3"}`,
		"retries float":          "{test: [curl], retries: 3.5}",
		"duplicate key":          "{test: [curl], interval: 10s, interval: 20s}",
		"array empty argument":   `[curl, ""]`,
		"array mapping argument": "[curl, {a: b}]",
	} {
		if _, err := Parse(healthDoc(hc)); err == nil {
			t.Errorf("%s: %s must be rejected", name, hc)
		}
	}
}

// An empty array has always meant "no healthcheck": it still parses, the canonical omits it,
// and nothing is generated.
func TestHealthcheckEmptyArrayIsNone(t *testing.T) {
	d, err := Parse(healthDoc("[]"))
	if err != nil {
		t.Fatalf("healthcheck: [] must still parse: %v", err)
	}
	canon, _ := Canonical(d)
	if strings.Contains(string(canon), "healthcheck") {
		t.Errorf("an empty healthcheck must be omitted from the canonical:\n%s", canon)
	}
	raw, err := ComposeBytes(d)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(raw), "healthcheck") {
		t.Errorf("an empty healthcheck must not be generated:\n%s", raw)
	}
}

func TestHealthcheckAccessorDefaults(t *testing.T) {
	var none *Healthcheck
	for _, h := range []*Healthcheck{none, {}, {Test: []string{"curl"}}} {
		if h.IntervalD() != 30*time.Second || h.TimeoutD() != 30*time.Second || h.RetriesN() != 3 || h.StartPeriodD() != 0 {
			t.Errorf("%+v: defaults = %v %v %d %v, want 30s 30s 3 0s", h, h.IntervalD(), h.TimeoutD(), h.RetriesN(), h.StartPeriodD())
		}
	}
	// A value validation would reject never leaks out of an accessor.
	bad := &Healthcheck{Test: []string{"curl"}, Interval: "soon", Timeout: "-5s", Retries: -2, StartPeriod: "x"}
	if bad.IntervalD() != 30*time.Second || bad.TimeoutD() != 30*time.Second || bad.RetriesN() != 3 || bad.StartPeriodD() != 0 {
		t.Errorf("unusable values must fall back to the defaults")
	}
}

func TestServiceSelfHealingOnUnhealthy(t *testing.T) {
	doc := func(sh string) []byte {
		return []byte(docWith("  compose:\n    services:\n      web:\n        image: nginx:1\n        healthcheck: [curl, -f, http://localhost/health]\n" + sh))
	}
	d, err := Parse(doc(""))
	if err != nil {
		t.Fatal(err)
	}
	if got := d.Spec.Compose.Services["web"].OnUnhealthy(); got != OnUnhealthyRestart {
		t.Errorf("unset on_unhealthy = %q, want restart", got)
	}
	if canon, _ := Canonical(d); strings.Contains(string(canon), "self_healing") {
		t.Errorf("an unset per-service self_healing must be omitted from the canonical:\n%s", canon)
	}
	for _, v := range []string{"restart", "notify"} {
		d, err := Parse(doc("        self_healing:\n          on_unhealthy: " + v + "\n"))
		if err != nil {
			t.Fatalf("on_unhealthy %s rejected: %v", v, err)
		}
		canon, err := Canonical(d)
		if err != nil {
			t.Fatal(err)
		}
		d2, err := Parse(canon)
		if err != nil {
			t.Fatalf("canonical did not re-parse: %v\n%s", err, canon)
		}
		if got := d2.Spec.Compose.Services["web"].OnUnhealthy(); got != v {
			t.Errorf("on_unhealthy %s round-tripped as %q:\n%s", v, got, canon)
		}
	}
	for name, sh := range map[string]string{
		"unknown value": "        self_healing:\n          on_unhealthy: ignore\n",
		"unknown key":   "        self_healing:\n          on_crash: notify\n",
		"app-level key": "        self_healing:\n          attempt_cap: 3\n",
	} {
		if _, err := Parse(doc(sh)); err == nil {
			t.Errorf("%s: must be rejected", name)
		}
	}
	// The per-service block doesn't disturb the app-level ladder tunables.
	both := docWith("  compose:\n    services:\n      web:\n        image: nginx:1\n        self_healing: {on_unhealthy: notify}\n  self_healing:\n    attempt_cap: 5\n")
	d, err = Parse([]byte(both))
	if err != nil {
		t.Fatalf("per-service + app-level self_healing rejected: %v", err)
	}
	if d.Spec.SelfHealing == nil || d.Spec.SelfHealing.AttemptCap != 5 || d.Spec.Compose.Services["web"].OnUnhealthy() != OnUnhealthyNotify {
		t.Errorf("self_healing blocks parsed wrong: app=%+v svc=%q", d.Spec.SelfHealing, d.Spec.Compose.Services["web"].OnUnhealthy())
	}
}
