package builder

import (
	"fmt"
)

// Each builder renders a hardened Dockerfile. The operator's install/build commands
// are sanitized to a single line (shellLine) so they can't inject extra directives;
// images run as a non-root user by default. These templates are sane starting points
// — an operator with an unusual build uses language: generic.

// --- node ---

type nodeBuilder struct{}

func (nodeBuilder) Name() string                  { return "node" }
func (nodeBuilder) Detect(f map[string]bool) bool { return f["package.json"] }
func (nodeBuilder) Dockerfile(s Spec, files map[string]bool) (string, error) {
	ver, err := version(s.Version, "20")
	if err != nil {
		return "", err
	}
	base := fmt.Sprintf("node:%s-alpine", ver)
	pkgs, err := packageLine("apk", s.Packages)
	if err != nil {
		return "", err
	}
	envs, err := envLines(s.Env)
	if err != nil {
		return "", err
	}
	// npm/yarn/pnpm from the committed lockfile (or an explicit build.install).
	pm := detectJSPM(files, s.Install)
	install, err := shellLine("build.install", orDefault(s.Install, pm.install))
	if err != nil {
		return "", err
	}
	build, err := shellLine("build.build", s.Build)
	if err != nil {
		return "", err
	}
	cmd, err := cmdLine(s.Start)
	if err != nil {
		return "", err
	}
	lines := []string{
		"# generated by Mooring — do not edit",
		"FROM " + base + " AS build",
		"WORKDIR /app",
	}
	// pnpm (and Yarn Berry) ship via Corepack, not the base image; provision it
	// non-interactively so the install can't hang waiting on a download prompt.
	if pm.corepack {
		lines = append(lines, "ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0", "RUN corepack enable")
	}
	lines = append(lines, pkgs)
	// Strip dev dependencies from the shipped image — the build stage needs them, the
	// runtime stage doesn't. Only when the manager offers a prune AND the effective
	// install ran the SAME manager (an operator who overrode install with an unrelated
	// command opts out, exactly as the historical npm-only check did).
	prune := ""
	if pm.prune != "" && firstWord(install) == pm.name {
		prune = "RUN " + pm.prune
	}
	lines = append(lines, envs...)
	if pm.copyAll {
		// Yarn Berry: the whole context (.yarnrc.yml, .yarn/releases) must be present to
		// resolve `yarn`, so copy everything before install (no cached install layer).
		lines = append(lines, "COPY "+s.src(".")+" .", "RUN "+install, runIf(build), prune)
	} else {
		lines = append(lines,
			// Copy manifests + lockfile first so the install layer caches until they
			// change (a source-only edit won't re-run the install).
			"COPY "+srcJoin(s, pm.manifests)+" ./",
			"RUN "+install,
			"COPY "+s.src(".")+" .",
			runIf(build),
			prune,
		)
	}
	lines = append(lines,
		"FROM "+base+" AS run",
		"WORKDIR /app",
		"COPY --from=build /app /app",
	)
	// Provision the manager in the runtime image too when the base image lacks it (pnpm),
	// so a `pnpm start`-style CMD doesn't crash with "not found". Runs as root, before the
	// USER drop below. Disable pnpm's packageManager self-switch first, so the freshly
	// installed (latest) pnpm runs the app's scripts directly instead of trying to fetch a
	// pinned version at container start — which would fail in an offline/air-gapped run.
	if pm.runtime != "" {
		lines = append(lines, "ENV npm_config_manage_package_manager_versions=false", "RUN "+pm.runtime)
	}
	lines = append(lines, nonrootIf(s.Nonroot, nonrootAlpine())...)
	lines = append(lines, cmd)
	return join(lines...), nil
}

// --- python ---

type pythonBuilder struct{}

func (pythonBuilder) Name() string { return "python" }
func (pythonBuilder) Detect(f map[string]bool) bool {
	return f["requirements.txt"] || f["pyproject.toml"] || f["Pipfile"]
}
func (pythonBuilder) Dockerfile(s Spec, files map[string]bool) (string, error) {
	ver, err := version(s.Version, "3.12")
	if err != nil {
		return "", err
	}
	base := fmt.Sprintf("python:%s-slim", ver) // debian slim: best wheel compatibility
	pkgs, err := packageLine("apt", s.Packages)
	if err != nil {
		return "", err
	}
	envs, err := envLines(s.Env)
	if err != nil {
		return "", err
	}
	// pip/poetry/pipenv from the committed lockfile (poetry.lock, Pipfile).
	install, err := shellLine("build.install", orDefault(s.Install, detectPyPM(files).install))
	if err != nil {
		return "", err
	}
	build, err := shellLine("build.build", s.Build)
	if err != nil {
		return "", err
	}
	cmd, err := cmdLine(s.Start)
	if err != nil {
		return "", err
	}
	lines := []string{
		"# generated by Mooring — do not edit",
		"FROM " + base,
		"WORKDIR /app",
		"ENV PYTHONUNBUFFERED=1 PIP_DISABLE_PIP_VERSION_CHECK=1",
		pkgs,
	}
	lines = append(lines, envs...)
	lines = append(lines, "COPY "+s.src(".")+" .", "RUN "+install, runIf(build))
	lines = append(lines, nonrootIf(s.Nonroot, nonrootDebian())...)
	lines = append(lines, cmd)
	return join(lines...), nil
}

// --- go ---

type goBuilder struct{}

func (goBuilder) Name() string                  { return "go" }
func (goBuilder) Detect(f map[string]bool) bool { return f["go.mod"] }

// Go modules is the only mainstream dependency manager, so there's no counterpart to
// detect (unlike node's npm/yarn/pnpm) — files is unused.
func (goBuilder) Dockerfile(s Spec, _ map[string]bool) (string, error) {
	ver, err := version(s.Version, "1.23")
	if err != nil {
		return "", err
	}
	envs, err := envLines(s.Env)
	if err != nil {
		return "", err
	}
	install, err := shellLine("build.install", orDefault(s.Install, "go mod download"))
	if err != nil {
		return "", err
	}
	// CGO off → a static binary that runs on a tiny base.
	build, err := shellLine("build.build", orDefault(s.Build, "CGO_ENABLED=0 go build -o /out/app ./..."))
	if err != nil {
		return "", err
	}
	cmd := `CMD ["/app/app"]`
	if len(s.Start) > 0 {
		if cmd, err = cmdLine(s.Start); err != nil {
			return "", err
		}
	}
	lines := []string{
		"# generated by Mooring — do not edit",
		fmt.Sprintf("FROM golang:%s-alpine AS build", ver),
		"WORKDIR /app",
	}
	lines = append(lines, envs...)
	lines = append(lines,
		"COPY "+s.src(".")+" .",
		"RUN "+install,
		"RUN "+build,
		"FROM alpine:3",
		"WORKDIR /app",
		"RUN apk add --no-cache ca-certificates",
		"COPY --from=build /out/app /app/app",
	)
	lines = append(lines, nonrootIf(s.Nonroot, nonrootAlpine())...)
	lines = append(lines, cmd)
	return join(lines...), nil
}

// --- ruby ---

type rubyBuilder struct{}

func (rubyBuilder) Name() string                  { return "ruby" }
func (rubyBuilder) Detect(f map[string]bool) bool { return f["Gemfile"] }

// Bundler is Ruby's de-facto dependency manager with no mainstream counterpart, so
// files is unused. (Dev/test gems are already excluded via BUNDLE_WITHOUT below.)
func (rubyBuilder) Dockerfile(s Spec, _ map[string]bool) (string, error) {
	ver, err := version(s.Version, "3.3")
	if err != nil {
		return "", err
	}
	base := fmt.Sprintf("ruby:%s-alpine", ver)
	pkgs, err := packageLine("apk", s.Packages)
	if err != nil {
		return "", err
	}
	envs, err := envLines(s.Env)
	if err != nil {
		return "", err
	}
	install, err := shellLine("build.install", orDefault(s.Install, "bundle install"))
	if err != nil {
		return "", err
	}
	build, err := shellLine("build.build", s.Build)
	if err != nil {
		return "", err
	}
	cmd, err := cmdLine(s.Start)
	if err != nil {
		return "", err
	}
	lines := []string{"# generated by Mooring — do not edit", "FROM " + base, "WORKDIR /app", pkgs}
	// Skip development/test gems in the shipped image.
	lines = append(lines, `ENV BUNDLE_WITHOUT="development:test"`)
	lines = append(lines, envs...)
	lines = append(lines, "COPY "+s.src(".")+" .", "RUN "+install, runIf(build))
	lines = append(lines, nonrootIf(s.Nonroot, nonrootAlpine())...)
	lines = append(lines, cmd)
	return join(lines...), nil
}

// --- php (apache; mod_php serves HTTP on :80, apache drops to www-data) ---

type phpBuilder struct{}

func (phpBuilder) Name() string                  { return "php" }
func (phpBuilder) Detect(f map[string]bool) bool { return f["composer.json"] || f["index.php"] }

// Composer is PHP's de-facto dependency manager with no mainstream counterpart, so
// files is unused.
func (phpBuilder) Dockerfile(s Spec, _ map[string]bool) (string, error) {
	ver, err := version(s.Version, "8.3")
	if err != nil {
		return "", err
	}
	pkgs, err := packageLine("apt", s.Packages)
	if err != nil {
		return "", err
	}
	envs, err := envLines(s.Env)
	if err != nil {
		return "", err
	}
	install, err := shellLine("build.install", s.Install) // e.g. composer install
	if err != nil {
		return "", err
	}
	build, err := shellLine("build.build", s.Build)
	if err != nil {
		return "", err
	}
	lines := []string{
		"# generated by Mooring — do not edit",
		fmt.Sprintf("FROM php:%s-apache", ver),
		"WORKDIR /var/www/html",
		pkgs,
		"COPY --from=composer:2 /usr/bin/composer /usr/bin/composer",
	}
	lines = append(lines, envs...)
	lines = append(lines, "COPY "+s.src(".")+" .", runIf(install), runIf(build))
	// apache starts as root and drops to www-data itself; an explicit USER would
	// break binding :80, so php is the documented exception to USER app.
	return join(lines...), nil
}

// --- static (nginx serving the repo, optional build step) ---

type staticBuilder struct{}

func (staticBuilder) Name() string                  { return "static" }
func (staticBuilder) Detect(f map[string]bool) bool { return f["index.html"] }
func (staticBuilder) Dockerfile(s Spec, files map[string]bool) (string, error) {
	envs, err := envLines(s.Env)
	if err != nil {
		return "", err
	}
	build, err := shellLine("build.build", s.Build)
	if err != nil {
		return "", err
	}
	install, err := shellLine("build.install", s.Install)
	if err != nil {
		return "", err
	}
	// If there's a build step, run it in a node stage then serve ONLY the built
	// output (not the source + node_modules); else serve the repo as-is. The output
	// dir defaults to "dist" — set build.output for a different one (e.g. "build").
	if build != "" || install != "" {
		ver, _ := version(s.Version, "20")
		out := s.Output
		if out == "" {
			out = "dist"
		}
		// npm/yarn/pnpm for the build stage (same detection as the node builder). No
		// prune step: only the built output ships, so node_modules is discarded anyway.
		pm := detectJSPM(files, s.Install)
		if install == "" && files["package.json"] {
			install = pm.install // a SPA build needs its deps; default to the detected manager
		}
		lines := []string{
			"# generated by Mooring — do not edit",
			fmt.Sprintf("FROM node:%s-alpine AS build", ver),
			"WORKDIR /app",
		}
		if pm.corepack {
			lines = append(lines, "ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0", "RUN corepack enable")
		}
		lines = append(lines, envs...)
		if pm.copyAll {
			// Yarn Berry: the whole context must be present to resolve `yarn`.
			lines = append(lines, "COPY "+s.src(".")+" .", runIf(install), runIf(build))
		} else {
			lines = append(lines, "COPY "+srcJoin(s, pm.manifests)+" ./", runIf(install), "COPY "+s.src(".")+" .", runIf(build))
		}
		lines = append(lines,
			"FROM nginx:alpine",
			fmt.Sprintf("COPY --from=build /app/%s /usr/share/nginx/html", out),
		)
		return join(lines...), nil
	}
	return join(
		"# generated by Mooring — do not edit",
		"FROM nginx:alpine",
		"COPY "+s.src(".")+" /usr/share/nginx/html",
	), nil
}

// --- generic (best effort: operator's base + commands) ---

type genericBuilder struct{}

func (genericBuilder) Name() string                { return "generic" }
func (genericBuilder) Detect(map[string]bool) bool { return false } // never auto-selected
func (genericBuilder) Dockerfile(s Spec, _ map[string]bool) (string, error) {
	if err := validImage(s.Base); err != nil {
		return "", err
	}
	pkgs, err := packageLine("apt", s.Packages) // best-effort: assume a debian-ish base
	if err != nil {
		return "", err
	}
	envs, err := envLines(s.Env)
	if err != nil {
		return "", err
	}
	install, err := shellLine("build.install", s.Install)
	if err != nil {
		return "", err
	}
	build, err := shellLine("build.build", s.Build)
	if err != nil {
		return "", err
	}
	cmd, err := cmdLine(s.Start)
	if err != nil {
		return "", err
	}
	lines := []string{"# generated by Mooring — do not edit", "FROM " + s.Base, "WORKDIR /app"}
	if pkgs != "" {
		lines = append(lines, pkgs)
	}
	lines = append(lines, envs...)
	lines = append(lines, "COPY "+s.src(".")+" .", runIf(install), runIf(build))
	lines = append(lines, nonrootIf(s.Nonroot, nonrootDebian())...)
	lines = append(lines, cmd)
	return join(lines...), nil
}

// --- small helpers ---

func orDefault(v, def string) string {
	if v == "" {
		return def
	}
	return v
}

// runIf returns a RUN line for a non-empty command, else "".
func runIf(cmd string) string {
	if cmd == "" {
		return ""
	}
	return "RUN " + cmd
}

// nonrootIf returns the non-root snippet when enabled, else nil.
func nonrootIf(on bool, snippet []string) []string {
	if !on {
		return nil
	}
	return snippet
}
